services:
  - type: web
    name: instafollowx
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_URL
        value: rediss://default:6hUrYZQkUF26SIgCkGkaKSDlsbWvZ5Nm@redis-17417.c301.ap-south-1-1.ec2.redns.redis-cloud.com:17417
      - key: SESSION_SECRET
        generateValue: true 
